# Generated by Django 3.2.4 on 2023-01-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=255, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.CharField(max_length=255, verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='hobbie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=255, verbose_name='nombres'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_doc',
            field=models.CharField(max_length=255, verbose_name='tipo_doc'),
        ),
    ]
